### ISSUE TITLE
[Feature request] Allow use of `$AWS_PROFILE` for s3 authentication

### ISSUE THREAD

**Issue by gforsyth** [blue-yonder/storefact#10]
For users who have expiring tokens it is often more convenient to point to a specific credential profile.  

This would mean that `access_key` and `secret_key` would only be required for S3 stores if there is no `AWS_PROFILE` or `AWS_DEFAULT_PROFILE` environment variable.

I'm happy to take a crack at this in the near future.

**Comment by fmarczin** [comment]
I see the value for your use case. What makes me hesitate is that this would make the code less pure, in the sense that the return value of `get_store()` is no longer determined by its arguments. 

Does boto recognize these environment variables? Are they in use anywhere else in public code?

**Comment by gforsyth** [comment]
They are part of `boto3` but not `botocore`: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variable-configuration

**Comment by joeschmid** [comment]
We have this feature request also. For security and compliance reasons, we never pass access_key and secret_key directly and instead use IAM roles/ec2 instance profiles so that credentials are provided automatically. We would like to use Kartothek, but this issue is a blocker for us. In our view, this represents a best practice for security on AWS: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#use-roles-with-ec2 

"Applications that run on an Amazon EC2 instance need credentials in order to access other AWS services. To provide credentials to the application in a secure way, use IAM roles. A role is an entity that has its own set of permissions, but that isn't a user or group. Roles also don't have their own permanent set of credentials the way IAM users do. In the case of Amazon EC2, IAM dynamically provides temporary credentials to the EC2 instance, and these credentials are automatically rotated for you."

Thanks for considering this!
