### ISSUE TITLE
Merge with or migrate to minimalkv

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/storefact#21]
As https://github.com/mbr/simplekv/issues/114 and https://github.com/mbr/simplekv/issues/113 are still unresolved, we have forked `simplekv` as `minimalkv` at a neutral place over at https://github.com/data-engineering-collective/minimalkv. As `storefact` is an essential addon to the usability of that, it would be nice to get it working with the new name. Personally, I did never understand whether there was a technical reason for the split and thus I would prefer merging `storefact` into `minimalkv`. Otherwise, I'm open to just updating the dependency here.

Happy to do the work, just wanted to be nice and reach out beforehand!

**Comment by fjetter** [comment]
I have the same feelings about the artificial split between the two repos. I like the idea of merging it with `minimalkv`

**Comment by felix-marczinowski-by** [comment]
I also agree that the split is artificial and merging makes a lot of sense.

I have one very very strong suggestion, though (a plea, even, on behalf of future-you and your users):
Use this opportunity to get rid of the pseudo-URL functionality. It is an inferior API and responsible for the majority of issues users have had with storefact:
- URL parameters have to be encoded/escaped. Pretty much every single user of the URL functionality has either been bitten by that or it's still a time bomb waiting to go off in their code. This is not the case with the core API, `get_store()`
- Store types and their parameters have to be replicated and modified with every change in simplekv: https://github.com/JDASoftwareGroup/storefact/blob/master/storefact/_urls.py#L54

Just look at the complexity of `_urls.py` vs. `get_store()` which is 14 LOC, including the wrapper feature.

I would also add that it provides no actual value, since the caller side already has to have a way of handling nested data structures for their config. And if they don't, going via JSON, YAML or any other format is going to be safer, more future-proof and no additional effort for the `minimalkv` maintainers.

**Comment by xhochy** [comment]
I wouldn't want to remove the URL functionality here (yet) as it is used in quite some places and would make the move to the new package (name) even harder. I would like to keep the iterations as small as possible. We can do that (breaking) change later but at the moment, it would complicate the situation even more.

**Comment by xhochy** [comment]
Fixed by https://github.com/data-engineering-collective/minimalkv/releases/tag/1.1.0
